modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://example.com/yourpack/chex/issues"

[[mods]]
modId="cosmic_horizons_extended"
version="${file.jarVersion}"
displayName="Cosmic Horizons Extended"
authors="YourName"
description='''
Forge addon providing extended rocket tiers, planet discovery, and GTCEu mineral tiers.
Data-driven configs. Optional integrations with Cosmic Horizons, GTCEu, KubeJS, FTB Quests.
'''

[[dependencies.cosmic_horizons_extended]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.cosmic_horizons_extended]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

# Optional soft dependencies
[[dependencies.cosmic_horizons_extended]]
modId="cosmichorizons"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.cosmic_horizons_extended]]
modId="cosmosunbound"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.cosmic_horizons_extended]]
modId="gtceu"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.cosmic_horizons_extended]]
modId="kubejs"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.cosmic_horizons_extended]]
modId="ftbquests"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.cosmic_horizons_extended]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"


