modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GPL-3.0 license"

[[mods]]
modId = "ldlib"
version = "1.0.45"
displayName = "LowDragLib"
authors = "KilaBash, WarmthDawn"
description = "Low Drag Lib, a library for rendering, gui, particles, synchronize"
logoFile = "icon.png"
displayURL = "https://github.com/Low-Drag-MC/"

[[dependencies.ldlib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ldlib]]
modId = "gtceu"
mandatory = true
versionRange = "[1.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ldlib]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"