
[behavior]
	#If true, under-tier suits are bounced back on dimension entry; otherwise apply debuffs.
	suitBounceBack = false

[fuelMapping]
	#Fluid ID for tier 1
	T1 = "cosmic_horizons_extended:kerosene"
	#Fluid ID for tier 2
	T2 = "cosmic_horizons_extended:cryo_lox"
	#Fluid ID for tier 3
	T3 = "cosmic_horizons_extended:kerosene"
	#Fluid ID for tier 4
	T4 = "cosmic_horizons_extended:cryo_lox"
	#Fluid ID for tier 5
	T5 = "cosmic_horizons_extended:lh2_lox"
	#Fluid ID for tier 6
	T6 = "cosmic_horizons_extended:lh2_lox"
	#Fluid ID for tier 7
	T7 = "cosmic_horizons_extended:lh2_lox"
	#Fluid ID for tier 8
	T8 = "cosmic_horizons_extended:lh2_lox"
	#Fluid ID for tier 9
	T9 = "cosmic_horizons_extended:lh2_lox"
	#Fluid ID for tier 10
	T10 = "cosmic_horizons_extended:lh2_lox"

