name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Gradle checks and data generation
        run: ./gradlew check forge:runData --stacktrace

      - name: Fail on generated data drift
        run: |
          git status --short
          git diff --exit-code
